# Generated by Django 3.2.16 on 2022-11-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackHabbit', '0003_auto_20221104_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecord',
            old_name='date',
            new_name='created_at',
        ),
    ]
